messages:
  onlyPlayers:
    de:
      'Du musst ein Spieler sein um diesen Befehl auszuf체hren'
    en:
      'You must be a player to perform this command'
  commandNotFound:
    de:
      'Der Befehl wurde nicht gefunden'
      en:
        'The command was not found'
  languageNotFound:
    de:
      'Die gew체nschte Sprache ist nicht verf체gbar oder falsch geschrieben'
      en:
        'The requested language is not available or is misspelled'
  languageSwitch:
    de:
      'Deine Sprache wurde ge채ndert'
      en:
        'Your language has been changed'
defaultLanguage:
  'de_DE'